name: stager
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.16.0"

dependencies:
  analyzer: ^4.2.0
  build: ^2.3.0
  flutter:
    sdk: flutter
  source_gen: ^1.2.2

dev_dependencies:
  build_runner: ^2.1.11
  lints: ^2.0.0
  test: ^1.16.0
